from .settings import COMPATIBILITY_BORDERLINE_HIGH, COMPATIBILITY_BORDERLINE_LOW, RESUME_MODULE_NAMES

__all__ = ["COMPATIBILITY_BORDERLINE_HIGH", "COMPATIBILITY_BORDERLINE_LOW", "RESUME_MODULE_NAMES"]
